all: eco-logo.pdf fsps-logo.pdf law-logo.pdf med-logo.pdf ped-logo.pdf phil-logo.pdf sci-logo.pdf fi-logo.pdf color/eco-logo.pdf color/fi-logo.pdf color/fsps-logo.pdf color/law-logo.pdf color/med-logo.pdf color/ped-logo.pdf color/phil-logo.pdf color/sci-logo.pdf

%.pdf: %.eps
	epstopdf $<
